src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BookRepository::class)]
class Book
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $Content = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $created = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    /**
     * @var Collection<int, Comment>
     */
    #[ORM\OneToMany(targetEntity: Comment::class, mappedBy: 'book', orphanRemoval: true)]
    private Collection $comments;

    #[ORM\ManyToOne(inversedBy: 'books')]
    #[ORM\JoinColumn(nullable: true)]
    private ?Category $category = null;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function __toString()
    {
        return $this -> title;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setId(int $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->Content;
    }

    public function setContent(?string $Content): static
    {
        $this->Content = $Content;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getCreated(): ?\DateTimeInterface
    {
        return $this->created;
    }

    public function setCreated(\DateTimeInterface $created): static
    {
        $this->created = $created;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setBook($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getBook() === $this) {
                $comment->setBook(null);
            }
        }

        return $this;
    }

}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Repository\BookRepository;
use App\Repository\CommentRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BookController extends AbstractController
{
    #[Route('/book', name: 'app_book')]
    public function index(BookRepository $bookRepository): Response
    {
        return $this -> render('pages/book/index.html.twig', [
            'title' => 'Book',
            'book' => $bookRepository->findAll(),
        ]);
    }

    #[Route(path: '/book/{id}', name: 'article')]
    public function article(Request $request, Book $book, CommentRepository $commentRepository): Response {

        $offset = max(0, $request -> query -> getInt('offset') );
        $paginator = $commentRepository -> getCommentsPaginator($book, $offset);

        return $this -> render( 'pages/book/article.html.twig', [
           'article' => $book,
           'comments' => $paginator,
           'previous' => $offset - CommentRepository::COMMENTS_PER_PAGE,
           'next' => $offset + CommentRepository::COMMENTS_PER_PAGE
        ] );
    }
}

templates/pages/book/article.html.twig
{% extends 'layout/base.html.twig' %}

{% block title%}
	{{ article.title }}
{% endblock %}

{% block body%}

	<div id="main">
		<h1>
			{{ article.title }}
		</h1>
		<h3>{{ article.category }}</h3>
		<small>{{ article.created|format_datetime('medium', 'short') }}</small>
		<div>
			{{ article.content | nl2br }}
		</div>

		{% if comments %}
			<div class="comments">
				<h2>Comments</h2>
				{% for comment in comments %}
					<div class="comment">
						<div class="comment--title">
							<div>{{ comment.author }}</div>
							<div>{{ comment.email }}</div>
						</div>
						<div class="comment--body">
							<div>{{ comment.text }}</div>
						</div>
					</div>
				{% endfor %}
			</div>

            {% if previous >= 0 %}
                <a href="{{ path('article', {id:article.id, offset: previous}) }}">Previous</a>
            {% endif %}

            {% if next < comments|length %}
                <a href="{{ path('article', {id:article.id, offset: next}) }}">Next</a>
            {% endif %}

		{% endif %}

	</div>
{% endblock %}

templates/pages/book/index.html.twig
{% extends 'layout/base.html.twig' %}

{% block title%}
	{{ title }}
{% endblock %}

{% block body%}

	<div id="main">
		<h1>{{ title }}</h1>
		<ul>
			{% for article in book %}
				<li>
					<a href="{{ path('article', { id: article.id }) }}">
						{{ article }}
					</a>
				</li>
			{% endfor %}
		</ul>
	</div>

{% endblock %}